require("windows")
require("common")
-- require('scenarioShortcuts')
-- require("countdown1")
require("switch-app")
require("reload")
-- require("spoon")

-- hs.hotkey.bind(Common.hyperKey, "W", function()
-- 	hs.alert.show("hello world")
-- end)
-- hs.loadSpoon("AClock")
-- hs.hotkey.bind(Common.hyperKey, "c", function()
-- 	spoon.AClock:toggleShow()
-- end)
-- hs.loadSpoon("ReloadConfiguration")
-- spoon.ReloadConfiguration:start()
